CREATE TABLE task (
    id VARCHAR(20) NOT NULL,
    exec_date VARCHAR(20) NOT NULL,
    contents VARCHAR(100) NOT NULL,
    priority INT NOT NULL,
    progress INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);